import UniverseAbstractions.Axioms.Universes
import UniverseAbstractions.Axioms.Universe.Identity
import UniverseAbstractions.Axioms.Universe.Functors
import UniverseAbstractions.Axioms.Universe.FunctorExtensionality
import UniverseAbstractions.Axioms.Universe.Singletons
import UniverseAbstractions.Axioms.Universe.Products
import UniverseAbstractions.Axioms.Universe.Equivalences
import UniverseAbstractions.Axioms.Universe.StandardEquivalences
import UniverseAbstractions.Axioms.Universe.TypeConstructors
import UniverseAbstractions.Axioms.Universe.DependentTypes.Properties
import UniverseAbstractions.Axioms.Universe.DependentTypes.Relations
import UniverseAbstractions.Axioms.Universe.DependentTypes.DependentFunctors
import UniverseAbstractions.Axioms.Universe.DependentTypes.DependentProducts
import UniverseAbstractions.Axioms.Universe.DependentTypes.Independent
import UniverseAbstractions.Axioms.Universe.FunctorialIdentities.IdentityQuantification
import UniverseAbstractions.Axioms.Universe.FunctorialIdentities.UniversalExtensionality
import UniverseAbstractions.Axioms.Universe.FunctorialIdentities.FunctorProperties

import UniverseAbstractions.Axioms.CategoryTheory.Basic
import UniverseAbstractions.Axioms.CategoryTheory.Functors

import UniverseAbstractions.Lemmas.DerivedFunctors
import UniverseAbstractions.Lemmas.DerivedFunctorExtensionality
import UniverseAbstractions.Lemmas.DerivedSingletonFunctors
import UniverseAbstractions.Lemmas.DerivedProductFunctors

import UniverseAbstractions.Tactics.Functoriality

import UniverseAbstractions.Instances.Utils.Trivial
import UniverseAbstractions.Instances.Utils.TrivialCategoryTheory
import UniverseAbstractions.Instances.Utils.Direct
import UniverseAbstractions.Instances.Utils.Bundled
import UniverseAbstractions.Instances.Basic
import UniverseAbstractions.Instances.FunctorUniverse
import UniverseAbstractions.Instances.CoFunctorUniverse
import UniverseAbstractions.Instances.Algebra
import UniverseAbstractions.Instances.Category
